// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHsVo_lEkr1hHczd4-h9iebDDZIH2t0UM',
    appId: '1:59419744409:android:25e0a9b935ce8f999f8008',
    messagingSenderId: '59419744409',
    projectId: 'bysell-29fc6',
    storageBucket: 'bysell-29fc6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbZlzyDurKHBZiS39cj826ZctNDeWXMSY',
    appId: '1:59419744409:ios:41f0871c8e859b189f8008',
    messagingSenderId: '59419744409',
    projectId: 'bysell-29fc6',
    storageBucket: 'bysell-29fc6.firebasestorage.app',
    androidClientId: '59419744409-0q1nb923jl92jdl26rv87g9n20h37ufl.apps.googleusercontent.com',
    iosClientId: '59419744409-o80c7islrnpsoqve8qi1d2gqllhj0sei.apps.googleusercontent.com',
    iosBundleId: 'com.slowbro.bysell',
  );

}